targets:
  $default:
    builders:
      json_serializable:
        options:
          field_rename: snake
          checked: true
          explicit_to_json: true
      envied_generator|envied:
        options:
          path: .env
          override: true
