name: iplant_api
description: A starting point for Dart libraries or applications.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0 

# Add regular dependencies here.
dependencies:
  change_case: ^2.2.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  html: ^0.15.4
  json_annotation: ^4.9.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  test: ^1.24.0
